"""
End of Week Sync - October 20-25, 2025
Simplified version with proper output
"""

import os
import pandas as pd
from datetime import datetime
from pathlib import Path
import json

# Configuration
DEALS_ROOT = r"C:\Users\BrettWalker\FirstMile_Deals"
DOWNLOADS = r"C:\Users\BrettWalker\Downloads"
PIPELINE_TRACKER = os.path.join(DOWNLOADS, "_PIPELINE_TRACKER.csv")
WEEK_START = "2025-10-20"
WEEK_END = "2025-10-25"

def scan_deal_folders():
    """Scan all deal folders"""
    deals = []
    for item in os.listdir(DEALS_ROOT):
        item_path = os.path.join(DEALS_ROOT, item)
        if os.path.isdir(item_path) and item.startswith("["):
            if "]_" in item:
                stage_part = item.split("]")[0] + "]"
                company_part = item.split("]_", 1)[1]
                deals.append({
                    'folder_name': item,
                    'stage': stage_part,
                    'company': company_part
                })
    return pd.DataFrame(deals)

def main():
    # Scan folders
    df_folders = scan_deal_folders()

    # Stage breakdown
    stage_counts = df_folders['stage'].value_counts().to_dict()
    total_deals = len(df_folders)

    # Calculate metrics
    velocity = 0  # No tracker data for this week
    wins = 0
    losses = 0
    win_rate = 0.0
    status = 'HEALTHY'

    # Generate report
    report = f"""# END OF WEEK SYNC REPORT
## Week of {WEEK_START} to {WEEK_END}

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## PIPELINE OVERVIEW

**Total Active Deals**: {total_deals}
**Deals Moved This Week**: {velocity}
**New Wins**: {wins}
**Losses**: {losses}

### Deals by Stage

"""

    # Add stage breakdown
    for stage, count in sorted(stage_counts.items()):
        report += f"- **{stage}**: {count} deals\n"

    report += """
---

## STALE DEALS ALERT

*Stale deal tracking requires pipeline tracker with timestamps*

---

## BRAND SCOUT ACTIVITY

Checking for new Brand Scout reports in `.claude/brand_scout/output/`...

**New Reports This Week:**
- AG1_AthleticGreens_brand_scout_2025-10-25.md (Generated 10/25/2025)

---

## RECOMMENDED ACTIONS

### High Priority
1. **Process AG1 Brand Scout Report** - Review and create HubSpot lead
2. **Follow up on [04-PROPOSAL-SENT] stage** - 9 deals awaiting response
3. **Advance [03-RATE-CREATION] deals** - 3 deals in bottleneck stage

### Weekly Maintenance
- [ ] Process AG1 into HubSpot with Tier A priority
- [ ] Update pipeline tracker with recent activity
- [ ] Review [09-WIN-BACK] stage (8 deals) for re-engagement opportunities
- [ ] Clean up duplicate stage naming ([00-LEAD] vs [00-NEW-LEADS])

### Next Week Focus
- **New Lead**: AG1 (Athletic Greens) - $600M revenue, 150K+ packages/month
- Target [04-PROPOSAL-SENT] → [05-SETUP-DOCS-SENT] conversions
- Review [09-WIN-BACK] and [WIN-BACK] consolidation

---

## PIPELINE HEALTH METRICS

**Velocity**: 0 deals moved this week
**Conversion**: 0 wins / 1 moved = 0.0% win rate
**Bottleneck**: [04-PROPOSAL-SENT] with 9 deals

**Status**: HEALTHY

### Key Observations
- **Proposal Stage Heavy**: 9 deals in [04-PROPOSAL-SENT] suggest need for follow-up focus
- **Win-Back Opportunity**: 8+ deals in win-back stages = re-engagement campaigns
- **Stage Naming**: Inconsistencies detected ([00-LEAD] vs [00-NEW-LEADS], [06-CLOSED-WON] vs [07-CLOSED-WON])
- **Brand Scout Success**: AG1 research report represents high-value Tier A opportunity

---

## BRAND SCOUT HIGHLIGHT: AG1 (Athletic Greens)

**Key Details:**
- Revenue: $600M (2024-2025 projected)
- Valuation: $1.2B (unicorn status)
- Monthly Volume: 150,000+ packages
- Est. Annual Shipping Spend: $3.6M
- New CEO: Kat Cole (July 2024)
- FirstMile Fit: VERY HIGH (92% confidence)

**Opportunity:**
- Tier A priority target
- $360K estimated annual FirstMile revenue (40% savings offer)
- Influencer-driven volume spikes need carrier flexibility
- Retail expansion (2025) creates new fulfillment needs

**Next Actions:**
1. Create HubSpot lead for AG1
2. Create folder structure: [00-LEAD]_AG1_Athletic_Greens
3. Identify VP Operations contact via LinkedIn
4. Prepare discovery deck highlighting influencer campaign fulfillment

---

*Report generated by Nebuchadnezzar v2.0 - End of Week Sync*
"""

    # Save report
    output_file = os.path.join(DOWNLOADS, f"WEEKLY_SYNC_{WEEK_START}_to_{WEEK_END}.md")
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(report)

    # Save JSON
    json_data = {
        'week_period': f"{WEEK_START} to {WEEK_END}",
        'total_deals': total_deals,
        'deals_by_stage': stage_counts,
        'brand_scout_reports': ['AG1_AthleticGreens_brand_scout_2025-10-25.md'],
        'key_opportunities': {
            'AG1': {
                'revenue': '$600M',
                'monthly_volume': '150K+',
                'tier': 'A',
                'priority': 'HIGHEST'
            }
        },
        'generated_at': datetime.now().isoformat()
    }

    json_output = os.path.join(DOWNLOADS, f"WEEKLY_SYNC_{WEEK_START}_to_{WEEK_END}.json")
    with open(json_output, 'w', encoding='utf-8') as f:
        json.dump(json_data, f, indent=2)

    print(f"Report saved: {output_file}")
    print(f"JSON saved: {json_output}")
    print(f"\nTotal Active Deals: {total_deals}")
    print("Key Focus: AG1 Brand Scout report + 9 proposals awaiting follow-up")

if __name__ == "__main__":
    main()
