name: Create BoxiiShip Reid Call Task

on:
  workflow_dispatch:

jobs:
  create-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create BoxiiShip Reid Call Task
        env:
          HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
        run: |
          python create_boxiiship_reid_call.py

      - name: Task creation summary
        run: |
          echo "✅ BoxiiShip Reid call task created"
          echo "Check HubSpot for task due tomorrow at 10 AM"
